name: node_js
on: 
  push:
    branches : [master] 
  pull_request: 
    branches : [master] 

jobs : 
  client :
    strategy :
      matrix :
         os: [ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    env :
         PACKAGE_LOCATION : client
    steps :
      - name : checkout repo
        uses : actions/checkout@v2
      - uses : use node.js ${{matrix.node-version}}
        with:
          node-version: lts/*
      - name : build 
        run : |
            cd $PACKAGE_LOCATION
            npm ci
            npm run format
            npm run lint
            npm run build
            npm run test
  server :
    strategy :
      matrix :
         os: [ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    env :
      PACKAGE_LOCATION=client
    steps :
      - name : checkout repo
        uses : actions/checkout@v2
      - uses : use node.js ${{matrix.node-version}}
        with:
          node-version: lts/*
      - name : build 
        run : |
            cd $PACKAGE_LOCATION
            npm ci
            npm run format
            npm run lint
            npm run build
            npm run test
      
